name: bscproject
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda=4.10.1
  - pandas=1.2.3
  - jupyter=1.0.0
  - scipy=1.6.2
  - biopython=1.78
  - statsmodels=0.12.2
  - matplotlib=3.4.1
  - numpy=1.20.2
  - tqdm=4.60.0
  - r-base=4.0.3
  - r-essentials=4.0
  - r-tidyverse=1.3.1
  - r-ggplot2=3.3.3
  - r-ggrepel=0.9.1
  - gffutils=0.10.1
  - git-lfs=2.13.2
  - pip:
    - more-itertools==8.7.0
    - peewee==3.14.4
    - taxadb==0.12.0
